name: Alpha Release

on:
  push:
    tags:
      - 'v*.*.*-alpha.*'
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        default: 'alpha'
        type: choice
        options:
        - alpha
        - alpha:patch
        - alpha:minor
        - alpha:major

permissions:
  contents: write
  id-token: write

jobs:
  alpha-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Configure Git
      if: github.event_name == 'workflow_dispatch'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Install dependencies
      run: bun install
    
    - name: Build
      run: bun run build
    
    - name: Check TypeScript
      run: bun run typecheck
    
    - name: Create alpha version (manual trigger)
      if: github.event_name == 'workflow_dispatch'
      run: |
        npm version prerelease --preid=alpha
        git push
        git push --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish alpha to npm
      run: npm publish --tag alpha --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Get version
      id: version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: v${{ steps.version.outputs.version }}
        body: |
          🧪 **Alpha Release** - This is a pre-release version for testing purposes.
          
          Install with: `npm install @timoaus/define-claude-code-hooks@alpha`
          
          **⚠️ Warning**: Alpha versions may contain breaking changes and are not recommended for production use.
        draft: false
        prerelease: true